"""Seed state_registry with US legislative data for non-IND exosome commercial pathway."""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.db import get_conn, init_db

# ── State data ────────────────────────────────────────────────────────────────
# legislation_type: 'right_to_try' | 'physician_exemption' | 'wellness_only' | 'none' | 'unclear'
# risk_level:       'low' | 'medium' | 'high' | 'unknown'
#
# Sources: training knowledge (cutoff Aug 2025). Priority states have confirmed bill numbers.
# CAUTION: Verify source_url links and exact statute codification before relying in legal context.
STATES_DATA = [
    {
        "state_code": "AL",
        "state_name": "Alabama",
        "legislation_type": "right_to_try",
        "key_provisions": "Alabama enacted a state Right to Try law (Dallas Buyers Club Act) covering terminal patients seeking experimental treatments. No specific stem cell or exosome exemption. No general physician exemption for wellness/aesthetics biologics.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "RTT limited to terminal diagnoses. Alabama Medical Licensure Commission has not issued specific guidance on exosomes. Risk is medium — no affirmative prohibition but no protective exemption either.",
        "source_url": "https://law.justia.com/codes/alabama/title-8/chapter-40/",
    },
    {
        "state_code": "AK",
        "state_name": "Alaska",
        "legislation_type": "right_to_try",
        "key_provisions": "Alaska enacted Right to Try (AS 08.64.364) for terminal patients. No physician exemption for general wellness biologics.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Remote/rural healthcare culture may mean lower enforcement scrutiny, but legal exposure remains.",
        "source_url": "https://law.justia.com/codes/alaska/title-8/chapter-64/section-08-64-364/",
    },
    {
        "state_code": "AZ",
        "state_name": "Arizona",
        "legislation_type": "right_to_try",
        "key_provisions": "Arizona is the origin state of the RTT movement. ARS §§ 36-1311 to 36-1316 (2014) cover terminal patients seeking access to investigational biologics. Includes physician protection clause shielding physicians from discipline for recommending investigational treatments to eligible terminal patients. No explicit wellness/aesthetics carve-out.",
        "effective_date": "2014-05-21",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Most physician-protective RTT statute but terminal patient requirement is firm. Exosome/stem cell clinics in Scottsdale rely on FDA enforcement discretion and practice-of-medicine doctrine, not this statute. AZSBME has pursued some disciplinary cases involving unapproved biologics. TODO: Check AZ Medical Board guidance post-2023.",
        "source_url": "https://www.azleg.gov/ars/36/01311.htm",
    },
    {
        "state_code": "AR",
        "state_name": "Arkansas",
        "legislation_type": "right_to_try",
        "key_provisions": "Arkansas enacted Right to Try (Ark. Code § 20-13-1201 et seq.) covering terminal patients. No physician exemption for wellness biologics.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell legislation. Arkansas State Medical Board follows standard guidelines. No known enforcement actions targeting exosome clinics as of mid-2025.",
        "source_url": "https://law.justia.com/codes/arkansas/title-20/subtitle-2/chapter-13/subchapter-12/",
    },
    {
        "state_code": "CA",
        "state_name": "California",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law, no physician exemption for unapproved biologics outside clinical trials. The Medical Practice Act and Sherman Food, Drug & Cosmetic Law provide comprehensive oversight. CDPH and Medical Board of California actively regulate and discipline around unapproved biologics.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "SB 512 (2018) added disclosure requirements for stem cell clinics but does not legalize unapproved products. FDA and California coordinate enforcement. Multiple cease-and-desist and disciplinary actions documented. High legal risk for exosome clinic operators.",
        "source_url": "https://www.mbc.ca.gov/",
    },
    {
        "state_code": "CO",
        "state_name": "Colorado",
        "legislation_type": "right_to_try",
        "key_provisions": "Colorado enacted Right to Try (CRS § 25-45-101 et seq.) for terminal patients. No general wellness or aesthetics exemption.",
        "effective_date": "2014",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Colorado Medical Board has not issued specific guidance on exosomes as of mid-2025. Some regenerative medicine clinics operate in Denver/Boulder. Enforcement risk is moderate.",
        "source_url": "https://leg.colorado.gov/sites/default/files/documents/2014A/bills/2014a_1184_enr.pdf",
    },
    {
        "state_code": "CT",
        "state_name": "Connecticut",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Strong state DPH oversight.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "CT DPH and Medical Examining Board enforce strictly. No known exosome-specific legislation or guidance. High-regulatory-environment state.",
        "source_url": "https://portal.ct.gov/DPH",
    },
    {
        "state_code": "DE",
        "state_name": "Delaware",
        "legislation_type": "right_to_try",
        "key_provisions": "Delaware enacted Right to Try (16 Del. C. § 9801 et seq.) for terminal patients. No broader wellness or aesthetics exemption.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Small state with limited specific enforcement history on exosomes. Standard medical board oversight applies.",
        "source_url": "https://delcode.delaware.gov/title16/c098/index.html",
    },
    {
        "state_code": "DC",
        "state_name": "District of Columbia",
        "legislation_type": "none",
        "key_provisions": "DC has no Right to Try law and no physician exemption for unapproved biologics. DC Health and Board of Medicine regulate tightly. Federal enforcement is particularly visible given proximity to FDA/NIH.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "Proximity to FDA headquarters makes DC a high-scrutiny environment. Operating an exosome clinic here carries very high regulatory exposure from both federal and local authorities.",
        "source_url": "https://dchealth.dc.gov/",
    },
    {
        "state_code": "FL",
        "state_name": "Florida",
        "legislation_type": "physician_exemption",
        "key_provisions": "SB 1628 / HB 1419 (enacted 2023, effective July 1, 2023): created FS § 499.02825 requiring clinics offering stem cell treatments to register with AHCA and make specific written disclosures to patients. Creates registration/disclosure regime (not an outright ban). Florida RTT (FS § 499.0295) covers terminal patients separately. Board of Medicine has historically less aggressive enforcement posture than CA toward regenerative medicine.",
        "effective_date": "2023-07-01",
        "physician_admin_allowed": 1,
        "wellness_allowed": 1,
        "aesthetics_allowed": 1,
        "risk_level": "low",
        "notes": "Florida is one of the most favorable states for exosome/regenerative medicine clinics. 2023 law requires: (1) AHCA registration, (2) written disclosure that treatment is not FDA-approved, (3) informed consent. Physicians who comply with disclosure requirements have strong protection. IMPORTANT: The 'stem cell treatment' definition in statute may or may not expressly cover exosomes (which are acellular) — legal counsel should confirm scope. TODO: verify SB 1628 exact definition covers secretome/exosomes.",
        "source_url": "https://www.flsenate.gov/Session/Bill/2023/1628",
    },
    {
        "state_code": "GA",
        "state_name": "Georgia",
        "legislation_type": "right_to_try",
        "key_provisions": "Georgia enacted Right to Try (OCGA § 31-1-13) for terminal patients. No specific stem cell or exosome exemption statute beyond RTT.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Active exosome/regen clinic ecosystem in Atlanta. Composite Medical Board has not issued specific exosome guidance as of mid-2025. Risk is medium — no protective statute but no active enforcement campaign either. Standard practice-of-medicine doctrine and informed consent are primary shields.",
        "source_url": "https://law.justia.com/codes/georgia/title-31/chapter-1/section-31-1-13/",
    },
    {
        "state_code": "HI",
        "state_name": "Hawaii",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. DCCA and the Medical Board regulate.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Limited known exosome clinic activity. No specific legislation. Isolated market means enforcement scrutiny may be lower in practice.",
        "source_url": "https://cca.hawaii.gov/pvl/boards/medical/",
    },
    {
        "state_code": "ID",
        "state_name": "Idaho",
        "legislation_type": "right_to_try",
        "key_provisions": "Idaho enacted Right to Try (Idaho Code § 39-9201 et seq.) for terminal patients. Strong liberty-oriented legislative culture; Board of Medicine has historically non-interventionist posture on alternative medicine.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "No affirmative legal protection for wellness/aesthetics use. Low enforcement risk in practice based on cultural/regulatory posture. No known enforcement actions targeting exosome clinics. Federal FDA jurisdiction remains.",
        "source_url": "https://legislature.idaho.gov/statutesrules/idstat/title39/t39ch92/",
    },
    {
        "state_code": "IL",
        "state_name": "Illinois",
        "legislation_type": "right_to_try",
        "key_provisions": "Illinois enacted Right to Try for terminal patients. IDFPR Medical Board regulates physicians. No general wellness exemption.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Illinois has an active medical board. No known specific exosome enforcement actions as of mid-2025. Chicago-area regenerative medicine market exists. Moderate risk.",
        "source_url": "https://www.ilga.gov/",
    },
    {
        "state_code": "IN",
        "state_name": "Indiana",
        "legislation_type": "right_to_try",
        "key_provisions": "Indiana enacted Right to Try (IC 16-21-12 et seq.) for terminal patients. Medical Licensing Board applies standard oversight.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific biologics/exosome exemption. Conservative state with limited specific enforcement history on exosomes.",
        "source_url": "https://iga.in.gov/laws/2015/ic/titles/16#16-21-12",
    },
    {
        "state_code": "IA",
        "state_name": "Iowa",
        "legislation_type": "right_to_try",
        "key_provisions": "Iowa enacted Right to Try (Iowa Code § 142D.1 et seq.) for terminal patients.",
        "effective_date": "2014",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Moderate regulatory environment. No known enforcement actions targeting exosome clinics.",
        "source_url": "https://www.legis.iowa.gov/law/iowaCode/sections?codeChapter=142D",
    },
    {
        "state_code": "KS",
        "state_name": "Kansas",
        "legislation_type": "right_to_try",
        "key_provisions": "Kansas enacted Right to Try (KSA § 65-6c01 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome legislation. Conservative state with no active enforcement campaign.",
        "source_url": "https://www.ksrevisor.org/statutes/chapters/ch65/065_006c_0001.html",
    },
    {
        "state_code": "KY",
        "state_name": "Kentucky",
        "legislation_type": "right_to_try",
        "key_provisions": "Kentucky enacted Right to Try (KRS § 217.9801 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Moderate regulatory environment.",
        "source_url": "https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=49543",
    },
    {
        "state_code": "LA",
        "state_name": "Louisiana",
        "legislation_type": "right_to_try",
        "key_provisions": "Louisiana enacted Right to Try (RS § 40:1285.1 et seq.) for terminal patients.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Louisiana medical culture is traditionally physician-autonomy-friendly but LSBME has disciplinary authority.",
        "source_url": "https://www.legis.la.gov/",
    },
    {
        "state_code": "ME",
        "state_name": "Maine",
        "legislation_type": "none",
        "key_provisions": "Maine has no Right to Try law. Board of Licensure in Medicine provides standard oversight. No physician exemption for unapproved biologics outside clinical trials.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Relatively small market; no known exosome enforcement actions.",
        "source_url": "https://www.maine.gov/md/",
    },
    {
        "state_code": "MD",
        "state_name": "Maryland",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Maryland Board of Physicians and MHD regulate strictly. NIH proximity makes federal enforcement particularly active in this region.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "High federal enforcement proximity (NIH, FDA CBER nearby). Maryland Board of Physicians takes a conservative stance. High risk for unapproved biologic administration.",
        "source_url": "https://www.mbp.state.md.us/",
    },
    {
        "state_code": "MA",
        "state_name": "Massachusetts",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Board of Registration in Medicine (BORIM) actively regulates. Strong academic medical culture means non-standard biologics are scrutinized.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "BORIM has broad disciplinary authority. AG's office has consumer protection jurisdiction. Framework is hostile to unapproved biologics marketed to patients.",
        "source_url": "https://www.mass.gov/orgs/board-of-registration-in-medicine",
    },
    {
        "state_code": "MI",
        "state_name": "Michigan",
        "legislation_type": "right_to_try",
        "key_provisions": "Michigan enacted Right to Try (MCL § 333.26451 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Michigan LARA/Board of Medicine is active, but no known exosome-specific enforcement campaign.",
        "source_url": "https://www.legislature.mi.gov/",
    },
    {
        "state_code": "MN",
        "state_name": "Minnesota",
        "legislation_type": "right_to_try",
        "key_provisions": "Minnesota enacted Right to Try (Minn. Stat. § 145.955 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome legislation. Strong healthcare infrastructure (Mayo Clinic) with conservative medical culture. Moderate enforcement risk.",
        "source_url": "https://www.revisor.mn.gov/statutes/cite/145.955",
    },
    {
        "state_code": "MS",
        "state_name": "Mississippi",
        "legislation_type": "right_to_try",
        "key_provisions": "Mississippi enacted Right to Try (Miss. Code § 41-139-1 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Conservative state with historically light-touch medical board enforcement on alternative therapies. No known exosome-specific enforcement actions. Practical risk is low, though no affirmative legal protection exists.",
        "source_url": "https://law.justia.com/codes/mississippi/title-41/chapter-139/",
    },
    {
        "state_code": "MO",
        "state_name": "Missouri",
        "legislation_type": "right_to_try",
        "key_provisions": "Missouri enacted Right to Try (RSMo § 191.480 et seq.) for terminal patients.",
        "effective_date": "2014",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Missouri has a moderately active regenerative medicine market. Enforcement risk is moderate.",
        "source_url": "https://revisor.mo.gov/main/OneSection.aspx?section=191.480",
    },
    {
        "state_code": "MT",
        "state_name": "Montana",
        "legislation_type": "physician_exemption",
        "key_provisions": "SB 88 (2019): explicitly prohibits the Montana Board of Medical Examiners from disciplining a physician solely for prescribing, recommending, or administering an investigational drug or biologic — including stem cell treatments — to a patient who has given informed consent. NOT limited to terminal patients. Removes state-level physician discipline risk without affirmatively authorizing the product.",
        "effective_date": "2019-10-01",
        "physician_admin_allowed": 1,
        "wellness_allowed": 1,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Montana SB 88 is one of the broadest state physician protection laws for investigational biologics. Key mechanism: removal of state board discipline authority, not affirmative authorization. Aesthetics use not explicitly addressed. Federal FDA enforcement remains possible. Board has not pursued exosome-specific cases since SB 88 passed. Maintain proper informed consent documentation.",
        "source_url": "https://leg.mt.gov/bills/2019/billpdf/SB0088.pdf",
    },
    {
        "state_code": "NE",
        "state_name": "Nebraska",
        "legislation_type": "right_to_try",
        "key_provisions": "Nebraska enacted Right to Try (Neb. Rev. Stat. § 71-9301 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Conservative state; moderate enforcement.",
        "source_url": "https://nebraskalegislature.gov/laws/statutes.php?statute=71-9301",
    },
    {
        "state_code": "NV",
        "state_name": "Nevada",
        "legislation_type": "right_to_try",
        "key_provisions": "Nevada enacted Right to Try (NRS § 454.253 et seq.) for terminal patients. Broadly permissive business regulatory culture and significant wellness/aesthetics industry in Las Vegas.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome exemption. Large aesthetics market means exosome use is present, but legal protection relies on informed consent and practice-of-medicine doctrine, not statute. Board of Medical Examiners retains authority to discipline.",
        "source_url": "https://www.leg.state.nv.us/NRS/NRS-454.html#NRS454Sec253",
    },
    {
        "state_code": "NH",
        "state_name": "New Hampshire",
        "legislation_type": "right_to_try",
        "key_provisions": "New Hampshire enacted Right to Try (RSA § 126-Z:1 et seq.) for terminal patients. NH's 'Live Free or Die' libertarian culture influences regulatory posture.",
        "effective_date": "2014",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "NH's libertarian culture translates to a less aggressive medical board posture on alternative therapies. No specific exosome/stem cell statute, but enforcement risk is practically low. No known enforcement actions targeting exosome clinics.",
        "source_url": "https://www.gencourt.state.nh.us/rsa/html/X/126-Z/126-Z-mrg.htm",
    },
    {
        "state_code": "NJ",
        "state_name": "New Jersey",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Division of Consumer Affairs / Board of Medical Examiners regulates strictly. NJ has among the most active state medical board enforcement in the country.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "Strong pharma/biotech industry presence creates political pressure for FDA-aligned standards. Board of Medical Examiners has prosecuted physicians for administering unapproved treatments. Framework is clearly hostile to unapproved biologics.",
        "source_url": "https://www.njconsumeraffairs.gov/bme",
    },
    {
        "state_code": "NM",
        "state_name": "New Mexico",
        "legislation_type": "right_to_try",
        "key_provisions": "New Mexico enacted Right to Try (NMSA § 24-27-1 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome statute. Moderately permissive regulatory culture for alternative therapies. Some integrative medicine activity in Santa Fe/Albuquerque. Moderate risk.",
        "source_url": "https://law.justia.com/codes/new-mexico/chapter-24/article-27/",
    },
    {
        "state_code": "NY",
        "state_name": "New York",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Office of Professional Medical Conduct (OPMC) aggressively disciplines physicians. Education Law § 6530 defines professional misconduct broadly.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "NY OPMC is one of the most active state medical enforcement bodies. AG's office also has consumer fraud jurisdiction. Multiple alternative medicine cases have resulted in license revocation. Very high risk.",
        "source_url": "https://www.health.ny.gov/professionals/doctors/conduct/",
    },
    {
        "state_code": "NC",
        "state_name": "North Carolina",
        "legislation_type": "right_to_try",
        "key_provisions": "North Carolina enacted Right to Try (NCGS § 90-325.3 et seq.) for terminal patients. NC Medical Board has issued guidance touching on evidence-based practice standards.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "NCMB has historically been moderately active on alternative therapy enforcement. Research Triangle biomedical culture may invite closer scrutiny. No specific exosome enforcement actions known as of mid-2025.",
        "source_url": "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_90/GS_90-325.3.html",
    },
    {
        "state_code": "ND",
        "state_name": "North Dakota",
        "legislation_type": "right_to_try",
        "key_provisions": "North Dakota enacted Right to Try (NDCC § 19-21-01 et seq.) for terminal patients.",
        "effective_date": "2015",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Small population, limited healthcare market. No known exosome clinic activity or enforcement actions. Practically low risk due to low regulatory activity, though no affirmative protection exists.",
        "source_url": "https://www.legis.nd.gov/cencode/t19c21.pdf",
    },
    {
        "state_code": "OH",
        "state_name": "Ohio",
        "legislation_type": "right_to_try",
        "key_provisions": "Ohio enacted Right to Try (ORC § 3792.01 et seq.) for terminal patients.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Ohio Medical Board is active. No specific exosome/stem cell statute. Cleveland Clinic and major academic centers create a conservative medical culture. Moderate enforcement risk.",
        "source_url": "https://codes.ohio.gov/ohio-revised-code/chapter-3792",
    },
    {
        "state_code": "OK",
        "state_name": "Oklahoma",
        "legislation_type": "right_to_try",
        "key_provisions": "Oklahoma enacted Right to Try (63 O.S. § 3080.1 et seq.) for terminal patients. Oklahoma has a generally conservative, pro-physician-autonomy legislative culture and was among the first states to pass RTT.",
        "effective_date": "2014",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Oklahoma Medical Board has a historically light-touch posture on alternative medicine. No specific exosome/stem cell exemption statute, but practical enforcement risk is low. No known enforcement actions targeting exosome clinics as of mid-2025.",
        "source_url": "https://www.oscn.net/applications/oscn/DeliverDocument.asp?CiteID=454568",
    },
    {
        "state_code": "OR",
        "state_name": "Oregon",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Oregon Medical Board provides standard, moderately active oversight.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Active naturopath and integrative medicine community, but MDs face standard rules. Naturopathic physicians have broader alternative therapy scope under OR law. Moderate risk for MD-administered exosome products.",
        "source_url": "https://www.oregon.gov/omb/",
    },
    {
        "state_code": "PA",
        "state_name": "Pennsylvania",
        "legislation_type": "right_to_try",
        "key_provisions": "Pennsylvania enacted Right to Try (35 P.S. § 5401 et seq.) for terminal patients.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Pittsburgh/Philadelphia academic medical culture is conservative. Moderate risk.",
        "source_url": "https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Medicine/Pages/default.aspx",
    },
    {
        "state_code": "RI",
        "state_name": "Rhode Island",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Small state; no known exosome clinic activity or enforcement actions. Standard medical board oversight applies.",
        "source_url": "https://health.ri.gov/licenses/detail.php?id=206",
    },
    {
        "state_code": "SC",
        "state_name": "South Carolina",
        "legislation_type": "right_to_try",
        "key_provisions": "South Carolina enacted Right to Try (SC Code § 44-130-10 et seq.) for terminal patients.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Conservative state; moderate enforcement posture. No known exosome-specific enforcement actions.",
        "source_url": "https://www.scstatehouse.gov/code/t44c130.php",
    },
    {
        "state_code": "SD",
        "state_name": "South Dakota",
        "legislation_type": "right_to_try",
        "key_provisions": "South Dakota enacted Right to Try (SDCL § 34-15A-1 et seq.) for terminal patients. Conservative, physician-autonomy-friendly legislative culture.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Small population, limited enforcement resources. No known exosome clinic activity or enforcement. Practical risk is low. No affirmative legal protection for wellness/aesthetics use.",
        "source_url": "https://sdlegislature.gov/",
    },
    {
        "state_code": "TN",
        "state_name": "Tennessee",
        "legislation_type": "right_to_try",
        "key_provisions": "Tennessee enacted Right to Try (TCA § 68-1-1801 et seq.) for terminal patients. Was among the first RTT states.",
        "effective_date": "2014",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome statute. Nashville healthcare corridor attracts regenerative medicine interest. Board of Medical Examiners has moderate enforcement posture. No known exosome-specific enforcement actions as of mid-2025.",
        "source_url": "https://www.tn.gov/health/health-professionals/medical/",
    },
    {
        "state_code": "TX",
        "state_name": "Texas",
        "legislation_type": "physician_exemption",
        "key_provisions": "Texas has the most comprehensive state-level framework for non-FDA-approved cell and biologic therapies. SB 1107 (2017): Innovative Treatment Program allows physicians at hospitals/ASCs to administer innovative treatments under IRB oversight. HB 810 (2017, Compassionate Use): expanded access, though limited to ALS/terminal under Texas law. Texas Medical Board Rule 200.3 governs stem cell/experimental treatment administration. RTT also enacted (HSC § 166.001 et seq.).",
        "effective_date": "2017-09-01",
        "physician_admin_allowed": 1,
        "wellness_allowed": 1,
        "aesthetics_allowed": 1,
        "risk_level": "low",
        "notes": "Texas is the most permissive large state for exosome/cell therapy clinics. SB 1107 Innovative Treatment Program exempts qualifying treatments from standard TX drug/device law under IRB oversight. Many TX exosome clinics operate outside IRB relying on practice-of-medicine doctrine and TMB's non-enforcement posture. Key caveats: (1) TMB Rule 200.3 requires specific documentation; (2) HB 810 Compassionate Use is limited to terminal/ALS under TX law — wellness/aesthetics must rely on SB 1107 or practice-of-medicine doctrine; (3) FDA enforcement still applies to product sellers.",
        "source_url": "https://www.legis.state.tx.us/BillLookup/History.aspx?LegSess=85R&Bill=SB1107",
    },
    {
        "state_code": "UT",
        "state_name": "Utah",
        "legislation_type": "physician_exemption",
        "key_provisions": "HB 272 (2018) extended Utah's RTT framework to 'seriously ill' patients (not just terminal), covering biologics including cell therapies. UC § 58-85-101 et seq. Utah Division of Professional Licensing (DOPL) instructed not to discipline physicians solely for administering treatment consistent with RTT provisions. Additional informed-consent protections (UC § 78B-3-468) for off-label/investigational use.",
        "effective_date": "2018-05-08",
        "physician_admin_allowed": 1,
        "wellness_allowed": 1,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "One of the strongest state-level physician protection frameworks outside FL and MT. The 'seriously ill' scope (vs terminal-only) is a key differentiator. Aesthetics marked 0 because statute's 'seriously ill' requirement likely excludes purely cosmetic/wellness patients with no underlying condition. DOPL has not pursued exosome-specific enforcement actions as of mid-2025. Utah integrative medicine and wellness market (SLC area) is active.",
        "source_url": "https://le.utah.gov/xcode/Title58/Chapter85/58-85.html",
    },
    {
        "state_code": "VT",
        "state_name": "Vermont",
        "legislation_type": "none",
        "key_provisions": "Vermont has no Right to Try law and no physician exemption for unapproved biologics. Vermont Medical Practice Board provides standard oversight.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Small state; no known exosome clinic activity. Standard oversight applies. Moderate risk in theory; low practical risk due to small market.",
        "source_url": "https://www.sec.state.vt.us/professional-regulation/list-of-professions/medicine.aspx",
    },
    {
        "state_code": "VA",
        "state_name": "Virginia",
        "legislation_type": "right_to_try",
        "key_provisions": "Virginia enacted Right to Try (Va. Code § 54.1-3442.1 et seq.) for terminal patients.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "Northern Virginia proximity to federal agencies (FDA, NIH) elevates enforcement visibility. Virginia Medical Board has moderate enforcement posture. Significant aesthetics and wellness market in Northern VA/DC suburbs. Moderate risk.",
        "source_url": "https://law.lis.virginia.gov/vacode/title54.1/chapter34/section54.1-3442.1/",
    },
    {
        "state_code": "WA",
        "state_name": "Washington",
        "legislation_type": "none",
        "key_provisions": "No Right to Try law and no physician exemption for unapproved biologics. Washington Medical Commission (WMC) provides active oversight. WMC has investigated practitioners for administering unapproved treatments.",
        "effective_date": "",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "high",
        "notes": "WMC is among the more active state medical commissions. Seattle biotech culture does not translate to regulatory permissiveness for unapproved biologics in clinical settings.",
        "source_url": "https://wmc.wa.gov/",
    },
    {
        "state_code": "WV",
        "state_name": "West Virginia",
        "legislation_type": "right_to_try",
        "key_provisions": "West Virginia enacted Right to Try (WV Code § 16-5X-1 et seq.) for terminal patients.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Small population, limited healthcare market, low enforcement resources. Conservative state with physician-autonomy culture. Practical risk is low. No known exosome clinic activity or enforcement actions.",
        "source_url": "https://code.wvlegislature.gov/16-5X/",
    },
    {
        "state_code": "WI",
        "state_name": "Wisconsin",
        "legislation_type": "right_to_try",
        "key_provisions": "Wisconsin enacted Right to Try for terminal patients. Wisconsin Medical Examining Board provides oversight.",
        "effective_date": "2016",
        "physician_admin_allowed": 0,
        "wellness_allowed": 0,
        "aesthetics_allowed": 0,
        "risk_level": "medium",
        "notes": "No specific exosome/stem cell statute. Wisconsin MEB has moderate enforcement posture. No known exosome-specific enforcement actions.",
        "source_url": "https://docs.legis.wisconsin.gov/",
    },
    {
        "state_code": "WY",
        "state_name": "Wyoming",
        "legislation_type": "physician_exemption",
        "key_provisions": "SF 57 (2019): Wyoming Access to Investigational Treatments Act (Wyo. Stat. § 35-35-101 et seq.). Allows any 'eligible patient' — chronic or seriously ill, not just terminal — to request investigational treatments including biologics. Explicitly prohibits WY Board of Medicine from disciplining a physician solely for recommending or administering an investigational treatment to an eligible patient who gave informed consent. No IRB oversight required (distinguishing WY from TX SB 1107).",
        "effective_date": "2019-07-01",
        "physician_admin_allowed": 1,
        "wellness_allowed": 1,
        "aesthetics_allowed": 0,
        "risk_level": "low",
        "notes": "Wyoming SF 57 is considered the most expansive state-level physician exemption for investigational biologics. Key limitations: (1) Patient must have qualifying 'serious or chronic illness' — pure aesthetics/wellness without underlying condition likely outside scope; (2) Product manufacturers/sellers remain subject to FDA; (3) Small population limits commercial scale. Aesthetics marked 0 because 'serious or chronic illness' eligibility likely excludes purely cosmetic patients. Wellness use for patients with chronic pain, inflammation, or joint issues likely qualifies.",
        "source_url": "https://www.wyoleg.gov/Legislation/2019/SF0057",
    },
]


def seed_states():
    init_db()
    today = datetime.now(timezone.utc).date().isoformat()

    with get_conn() as conn:
        for row in STATES_DATA:
            conn.execute(
                """INSERT OR REPLACE INTO state_registry
                   (state_code, state_name, legislation_type, key_provisions, effective_date,
                    physician_admin_allowed, wellness_allowed, aesthetics_allowed,
                    risk_level, notes, source_url, last_updated)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    row["state_code"], row["state_name"], row["legislation_type"],
                    row["key_provisions"], row.get("effective_date", ""),
                    row.get("physician_admin_allowed", 0), row.get("wellness_allowed", 0),
                    row.get("aesthetics_allowed", 0), row["risk_level"],
                    row.get("notes", ""), row.get("source_url", ""), today,
                ),
            )

    counts: dict[str, int] = {}
    for row in STATES_DATA:
        lvl = row.get("risk_level", "unknown")
        counts[lvl] = counts.get(lvl, 0) + 1

    print(f"\nSeeded {len(STATES_DATA)} states + DC:")
    for lvl, n in sorted(counts.items()):
        print(f"  {lvl}: {n}")


if __name__ == "__main__":
    seed_states()
